version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: manas
            MYSQL_PASSWORD: manas
    php:
        build: ./php
        expose:
            - "80:80"
        volumes:
            - ./symfony-app:/var/www/html
        links:
            - db