version: '2'
services:
    db:
        build: ./mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: manas
            MYSQL_PASSWORD: manas
        volumes:
            - ./data/db:/var/lib/mysql
    php:
        build: ./php
        ports:
            - "80:80"
        links:
            - db
        volumes:
            - ./symfony-app:/var/www/html