version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: canvanizerbeta
            MYSQL_USER: manas
            MYSQL_PASSWORD: manas
    php:
        build: ./php
        ports:
            - "80:80"
        links:
            - db
        volumes:
            - ./symfony-app:/var/www/html